### ISSUE TITLE
Export / Import 

### ISSUE THREAD

**Issue by in4matix** [kando-menu/menu-themes#2]
It would be a lot easier if users could export and inport menu themes like Fly-Pie.

**Comment by in4matix** [comment]
Hi, I meant, like in Fly-Pie, the ability to export menus to a file, instead of the user having to understand code to create a menu theme. So in the repo you can just have the one file that can then be imported into Kando. No coding required...

**Comment by Schneegans** [comment]
Sorry, but I am now properly confused. Are you talking about _menu themes_? Like the style, color, animations? Or are you talking about the individual menu configurations? Like the individual menus you set up in Kando's menu editor?

**Comment by in4matix** [comment]
I think I properly confused myself too. I have two identical pc's for home and work. When I want the same menus on both pc's, I export them on the one and import them on the other. Maybe this will clarify?

![Screenshot from 2024-11-21 07-37-54](https://github.com/user-attachments/assets/6ccc0e50-b5dd-4c9d-aacf-6f8e772f02d8)
